[package]
name = "metro-map-editor"
version = "0.1.0"
edition = "2021"

[dependencies]
leptos = { version = "0.6.14", features = ["csr", "nightly"] }
web-sys = { version = "0.3", features = [
    "KeyboardEvent",
    "HtmlCanvasElement",
    "HtmlInputElement",
    "FileList",
    "File",
    "Blob",
    "CanvasRenderingContext2d",
    "CssStyleDeclaration",
    "Element",
    "Window",
] }
wasm-bindgen = { version = "0.2" }
console_log = "1"
log = "0.4"
console_error_panic_hook = "0.1"
quick-xml = { version = "0.36.0", features = ["serialize"] }
serde_json = "1.0"
serde = { version = "1", features = ["derive"] }
