[build]
# The index HTML file to drive the bundling process.
target = "index.html"
# The output dir for all final assets.
dist = "dist"
# The public URL from which assets are to be served.
public_url = "/university/metro-map"

[serve]
# The port on which the development server should run.
port = 8080
# The host address on which the development server should run.
addresses = ["127.0.0.1"]
