name: Check

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Prepare
        run: |
          rustup update
          rustup component add clippy
          cargo install --locked trunk
      - name: Check
        run: cargo check
      - name: Build
        run: trunk build
      - name: Test
        run: cargo test
      - name: Lint
        run: |
          cargo clippy -- -D warnings
