name: Check

on: push

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Prepare
        run: |
          rustup toolchain install nightly
          rustup update
          cargo install --locked trunk
          rustup default nightly
          rustup target add wasm32-unknown-unknown
          rustup component add clippy
      - name: Check
        run: cargo check
      - name: Build
        run: trunk build
      - name: Test
        run: cargo test
      - name: Bench
        run: cargo bench -F benchmarking
      - name: Lint
        run: |
          cargo clippy -- -D warnings
